package main

import (
	"bufio"
	"crypto/tls"
	"encoding/base64"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	defaultEgressProxyAddr = "127.0.0.1:8118"
	defaultTorSocksAddr    = "127.0.0.1:9050"
	egressProfilePath      = "/etc/profile.d/sandbox-egress.sh"
	egressUpstreamTypeKey  = "SANDBOX_EGRESS_UPSTREAM_TYPE"
	egressUpstreamAddrKey  = "SANDBOX_EGRESS_UPSTREAM_ADDR"

	egressUpstreamTypeHTTP   = "http"
	egressUpstreamTypeHTTPS  = "https"
	egressUpstreamTypeSOCKS5 = "socks5"
	egressUpstreamTypeTor    = "tor"
)

var egressAppEnvKeys = []string{
	"HTTP_PROXY",
	"http_proxy",
	"HTTPS_PROXY",
	"https_proxy",
	"ALL_PROXY",
	"all_proxy",
	"NO_PROXY",
	"no_proxy",
}

type egressRequest struct {
	Environment map[string]string `json:"environment"`
}

type egressConfig struct {
	UpstreamType string
	UpstreamAddr string
}

type httpProxyTarget struct {
	URL    *url.URL
	UseTLS bool
}

type egressManager struct {
	mu     sync.RWMutex
	env    map[string]string
	config egressConfig
}

var egressState = newEgressManager()

func newEgressManager() *egressManager {
	env := currentProcessEgressEnv()
	config := egressConfig{
		UpstreamType: os.Getenv(egressUpstreamTypeKey),
		UpstreamAddr: os.Getenv(egressUpstreamAddrKey),
	}
	return &egressManager{env: env, config: config}
}

func handleEgress(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req egressRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "invalid request body", http.StatusBadRequest)
		return
	}

	next, config, err := egressEnvFromRequest(req.Environment)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if err := egressState.Set(next, config); err != nil {
		http.Error(w, "failed to update egress", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write([]byte(`{"ok":true}`))
}

func (m *egressManager) Set(env map[string]string, config egressConfig) error {
	if err := writeEgressProfile(env); err != nil {
		return err
	}

	m.mu.Lock()
	m.env = env
	m.config = config
	m.mu.Unlock()
	return nil
}

func (m *egressManager) RuntimeEnvironmentOverlay() []string {
	m.mu.RLock()
	defer m.mu.RUnlock()

	overlay := make([]string, 0, len(egressEnvKeys()))
	for _, key := range egressAppEnvKeys {
		overlay = append(overlay, key+"="+m.env[key])
	}
	overlay = append(overlay, egressUpstreamTypeKey+"=", egressUpstreamAddrKey+"=")
	return overlay
}

func (m *egressManager) Config() egressConfig {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.config
}

func egressEnvFromRequest(env map[string]string) (map[string]string, egressConfig, error) {
	next := make(map[string]string)
	for _, key := range egressAppEnvKeys {
		if value, ok := env[key]; ok {
			next[key] = value
		}
	}
	config := egressConfig{
		UpstreamType: env[egressUpstreamTypeKey],
		UpstreamAddr: env[egressUpstreamAddrKey],
	}
	if !isSupportedEgressUpstreamType(config.UpstreamType) {
		return nil, egressConfig{}, fmt.Errorf("unsupported upstream proxy type: %s", config.UpstreamType)
	}
	if err := validateEgressConfig(config); err != nil {
		return nil, egressConfig{}, err
	}
	return next, config, nil
}

func isSupportedEgressUpstreamType(value string) bool {
	switch value {
	case "", egressUpstreamTypeHTTP, egressUpstreamTypeHTTPS, egressUpstreamTypeSOCKS5, egressUpstreamTypeTor:
		return true
	default:
		return false
	}
}

func validateEgressConfig(config egressConfig) error {
	switch config.UpstreamType {
	case "":
		if config.UpstreamAddr != "" {
			return fmt.Errorf("upstream address requires an upstream proxy type")
		}
	case egressUpstreamTypeTor:
		if config.UpstreamAddr != "" {
			return fmt.Errorf("tor egress does not accept an upstream address")
		}
	case egressUpstreamTypeHTTP, egressUpstreamTypeHTTPS, egressUpstreamTypeSOCKS5:
		if config.UpstreamAddr == "" {
			return fmt.Errorf("upstream address is required for %s egress", config.UpstreamType)
		}
	}
	return nil
}

func writeEgressProfile(env map[string]string) error {
	var b strings.Builder
	b.WriteString("# Generated by sandbox-proxy. Do not edit.\n")
	for _, key := range egressEnvKeys() {
		b.WriteString("unset ")
		b.WriteString(key)
		b.WriteString("\n")
	}

	keys := make([]string, 0, len(env))
	for key := range env {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		b.WriteString("export ")
		b.WriteString(key)
		b.WriteString("=")
		b.WriteString(shellQuote(env[key]))
		b.WriteString("\n")
	}
	return os.WriteFile(egressProfilePath, []byte(b.String()), 0644)
}

func currentProcessEgressEnv() map[string]string {
	env := make(map[string]string)
	for _, key := range egressAppEnvKeys {
		if value := os.Getenv(key); value != "" {
			env[key] = value
		}
	}
	return env
}

func egressEnvKeys() []string {
	keys := append([]string{}, egressAppEnvKeys...)
	return append(keys, egressUpstreamTypeKey, egressUpstreamAddrKey)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func newEgressProxyServer() *http.Server {
	return &http.Server{
		Addr:              defaultEgressProxyAddr,
		Handler:           http.HandlerFunc(handleEgressProxyRequest),
		ReadHeaderTimeout: 10 * time.Second,
	}
}

func handleEgressProxyRequest(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodConnect {
		handleEgressConnect(w, r)
		return
	}
	handleEgressHTTP(w, r)
}

func handleEgressHTTP(w http.ResponseWriter, r *http.Request) {
	target := r.URL
	if !target.IsAbs() {
		http.Error(w, "absolute proxy URL required", http.StatusBadRequest)
		return
	}

	upstream, useProxyFormat, proxyAuth, err := dialEgressHTTP(target)
	if err != nil {
		log.Printf("egress HTTP dial failed target=%s upstream=%s: %v", target.Host, egressState.Config().LogLabel(), err)
		http.Error(w, "failed to connect upstream", http.StatusBadGateway)
		return
	}
	defer upstream.Close()

	req := r.Clone(r.Context())
	req.RequestURI = ""
	if useProxyFormat {
		req.URL = absoluteFormURL(target)
	} else {
		req.URL = originFormURL(target)
	}
	req.Header = cloneHeaderWithoutHopByHop(r.Header)
	req.Header.Del("Proxy-Authorization")
	req.Header.Del("Proxy-Connection")
	if proxyAuth != "" {
		req.Header.Set("Proxy-Authorization", proxyAuth)
	}

	if err := writeEgressHTTPRequest(req, upstream, useProxyFormat); err != nil {
		log.Printf("egress HTTP write failed target=%s: %v", target.Host, err)
		http.Error(w, "failed to write upstream request", http.StatusBadGateway)
		return
	}
	writeEgressResponse(w, upstream)
}

func handleEgressConnect(w http.ResponseWriter, r *http.Request) {
	upstream, err := dialEgressTunnel(r.Host, "443")
	if err != nil {
		log.Printf("egress CONNECT failed target=%s upstream=%s: %v", r.Host, egressState.Config().LogLabel(), err)
		if statusErr, ok := err.(*httpProxyStatusError); ok {
			http.Error(w, statusErr.Status, statusErr.StatusCode)
			return
		}
		http.Error(w, "failed to connect upstream", http.StatusBadGateway)
		return
	}
	defer upstream.Close()

	hijacker, ok := w.(http.Hijacker)
	if !ok {
		http.Error(w, "hijack unsupported", http.StatusInternalServerError)
		return
	}
	client, _, err := hijacker.Hijack()
	if err != nil {
		return
	}
	defer client.Close()

	_, _ = client.Write([]byte("HTTP/1.1 200 Connection Established\r\n\r\n"))
	relay(client, upstream)
}

func dialEgressHTTP(target *url.URL) (net.Conn, bool, string, error) {
	config := egressState.Config()
	address := ensurePort(target.Host, defaultPortForURL(target))
	if config.UpstreamType == "" {
		conn, err := net.DialTimeout("tcp", address, 15*time.Second)
		return conn, false, "", err
	}
	switch config.UpstreamType {
	case egressUpstreamTypeHTTP, egressUpstreamTypeHTTPS:
		conn, proxy, err := dialHTTPProxy(config)
		if err != nil {
			return nil, false, "", err
		}
		return conn, true, proxyAuthorizationHeader(proxy.URL), nil
	case egressUpstreamTypeSOCKS5:
		conn, err := dialViaSocks5Proxy(config.UpstreamAddr, address)
		return conn, false, "", err
	case egressUpstreamTypeTor:
		conn, err := dialViaTorProxy(address)
		return conn, false, "", err
	default:
		return nil, false, "", fmt.Errorf("unsupported upstream proxy type: %s", config.UpstreamType)
	}
}

func dialEgressTunnel(target string, defaultPort string) (net.Conn, error) {
	target = ensurePort(target, defaultPort)
	config := egressState.Config()
	if config.UpstreamType == "" {
		return net.DialTimeout("tcp", target, 15*time.Second)
	}
	switch config.UpstreamType {
	case egressUpstreamTypeHTTP, egressUpstreamTypeHTTPS:
		return dialViaHTTPProxy(config, target)
	case egressUpstreamTypeSOCKS5:
		return dialViaSocks5Proxy(config.UpstreamAddr, target)
	case egressUpstreamTypeTor:
		return dialViaTorProxy(target)
	default:
		return nil, fmt.Errorf("unsupported upstream proxy type: %s", config.UpstreamType)
	}
}

func dialViaHTTPProxy(config egressConfig, target string) (net.Conn, error) {
	conn, proxy, err := dialHTTPProxy(config)
	if err != nil {
		return nil, err
	}

	if err := writeHTTPProxyConnect(conn, target, proxyAuthorizationHeader(proxy.URL)); err != nil {
		conn.Close()
		return nil, err
	}
	return conn, nil
}

func dialHTTPProxy(config egressConfig) (net.Conn, httpProxyTarget, error) {
	proxy, err := parseHTTPProxyTarget(config.UpstreamType, config.UpstreamAddr)
	if err != nil {
		return nil, httpProxyTarget{}, err
	}

	conn, err := net.DialTimeout("tcp", proxy.URL.Host, 15*time.Second)
	if err != nil {
		return nil, httpProxyTarget{}, err
	}
	if proxy.UseTLS {
		tlsConn := tls.Client(conn, &tls.Config{ServerName: proxy.URL.Hostname()})
		if err := tlsConn.Handshake(); err != nil {
			conn.Close()
			return nil, httpProxyTarget{}, err
		}
		conn = tlsConn
	}
	return conn, proxy, nil
}

func writeHTTPProxyConnect(conn net.Conn, target string, proxyAuth string) error {
	var b strings.Builder
	b.WriteString("CONNECT ")
	b.WriteString(target)
	b.WriteString(" HTTP/1.1\r\nHost: ")
	b.WriteString(target)
	b.WriteString("\r\n")
	if proxyAuth != "" {
		b.WriteString("Proxy-Authorization: ")
		b.WriteString(proxyAuth)
		b.WriteString("\r\n")
	}
	b.WriteString("\r\n")
	if _, err := io.WriteString(conn, b.String()); err != nil {
		return err
	}

	resp, err := http.ReadResponse(bufio.NewReader(conn), &http.Request{Method: http.MethodConnect})
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		return &httpProxyStatusError{StatusCode: resp.StatusCode, Status: resp.Status}
	}
	return nil
}

type httpProxyStatusError struct {
	StatusCode int
	Status     string
}

func (e *httpProxyStatusError) Error() string {
	return "http proxy connect failed: " + e.Status
}

func (c egressConfig) LogLabel() string {
	if c.UpstreamAddr == "" {
		if c.UpstreamType == egressUpstreamTypeTor {
			return "tor://" + defaultTorSocksAddr
		}
		return "direct"
	}
	host := c.UpstreamAddr
	if _, _, address, ok := splitUserinfoHost(c.UpstreamAddr); ok {
		host = address
	}
	return c.UpstreamType + "://" + host
}

func dialViaTorProxy(target string) (net.Conn, error) {
	return dialViaSocks5Proxy(defaultTorSocksAddr, target)
}

func dialViaSocks5Proxy(upstream string, target string) (net.Conn, error) {
	user, password, address := splitUpstreamAuth(upstream)
	conn, err := net.DialTimeout("tcp", ensurePort(address, "1080"), 15*time.Second)
	if err != nil {
		return nil, err
	}
	if err := socks5Handshake(conn, user, password, target); err != nil {
		conn.Close()
		return nil, err
	}
	return conn, nil
}

func socks5Handshake(conn net.Conn, user string, password string, target string) error {
	methods := []byte{0x00}
	if user != "" {
		methods = []byte{0x00, 0x02}
	}
	hello := []byte{0x05, byte(len(methods))}
	hello = append(hello, methods...)
	if _, err := conn.Write(hello); err != nil {
		return err
	}

	reply := make([]byte, 2)
	if _, err := io.ReadFull(conn, reply); err != nil {
		return err
	}
	if reply[0] != 0x05 || reply[1] == 0xff {
		return fmt.Errorf("socks5 method rejected")
	}
	switch reply[1] {
	case 0x00:
	case 0x02:
		if len(user) > 255 || len(password) > 255 {
			return fmt.Errorf("socks5 credentials too long")
		}
		auth := []byte{0x01, byte(len(user))}
		auth = append(auth, []byte(user)...)
		auth = append(auth, byte(len(password)))
		auth = append(auth, []byte(password)...)
		if _, err := conn.Write(auth); err != nil {
			return err
		}
		if _, err := io.ReadFull(conn, reply); err != nil {
			return err
		}
		if reply[1] != 0x00 {
			return fmt.Errorf("socks5 authentication failed")
		}
	default:
		return fmt.Errorf("unsupported socks5 authentication method: %d", reply[1])
	}

	host, port, err := splitHostPortDefault(target, "443")
	if err != nil {
		return err
	}
	portNum, err := strconv.Atoi(port)
	if err != nil || portNum < 1 || portNum > 65535 {
		return fmt.Errorf("invalid target port: %s", port)
	}

	req := []byte{0x05, 0x01, 0x00}
	if ip := net.ParseIP(host); ip != nil {
		if ip4 := ip.To4(); ip4 != nil {
			req = append(req, 0x01)
			req = append(req, ip4...)
		} else {
			req = append(req, 0x04)
			req = append(req, ip.To16()...)
		}
	} else {
		if len(host) > 255 {
			return fmt.Errorf("target host too long")
		}
		req = append(req, 0x03, byte(len(host)))
		req = append(req, []byte(host)...)
	}
	portBytes := make([]byte, 2)
	binary.BigEndian.PutUint16(portBytes, uint16(portNum))
	req = append(req, portBytes...)
	if _, err := conn.Write(req); err != nil {
		return err
	}

	head := make([]byte, 4)
	if _, err := io.ReadFull(conn, head); err != nil {
		return err
	}
	if head[1] != 0x00 {
		return fmt.Errorf("socks5 connect failed: %d", head[1])
	}
	switch head[3] {
	case 0x01:
		_, err = io.CopyN(io.Discard, conn, 4)
	case 0x03:
		var length [1]byte
		if _, err = io.ReadFull(conn, length[:]); err != nil {
			return err
		}
		_, err = io.CopyN(io.Discard, conn, int64(length[0]))
	case 0x04:
		_, err = io.CopyN(io.Discard, conn, 16)
	default:
		err = fmt.Errorf("invalid socks5 address type: %d", head[3])
	}
	if err != nil {
		return err
	}
	_, err = io.CopyN(io.Discard, conn, 2)
	return err
}

func writeEgressResponse(w http.ResponseWriter, upstream net.Conn) {
	resp, err := http.ReadResponse(bufio.NewReader(upstream), nil)
	if err != nil {
		http.Error(w, "failed to read upstream response", http.StatusBadGateway)
		return
	}
	defer resp.Body.Close()

	copyHeader(w.Header(), cloneHeaderWithoutHopByHop(resp.Header))
	w.WriteHeader(resp.StatusCode)
	_, _ = io.Copy(w, resp.Body)
}

func writeEgressHTTPRequest(req *http.Request, conn net.Conn, useProxyFormat bool) error {
	if useProxyFormat {
		return req.WriteProxy(conn)
	}
	return req.Write(conn)
}

func parseHTTPProxyTarget(proxyType string, upstream string) (httpProxyTarget, error) {
	rawURL := "http://" + upstream
	proxyURL, err := url.Parse(rawURL)
	if err != nil {
		return httpProxyTarget{}, err
	}
	useTLS := proxyType == egressUpstreamTypeHTTPS
	defaultPort := "8080"
	if useTLS {
		defaultPort = "443"
	}
	proxyURL.Host = ensurePort(proxyURL.Host, defaultPort)
	return httpProxyTarget{URL: proxyURL, UseTLS: useTLS}, nil
}

func proxyAuthorizationHeader(proxyURL *url.URL) string {
	if proxyURL.User == nil {
		return ""
	}
	password, _ := proxyURL.User.Password()
	token := base64.StdEncoding.EncodeToString([]byte(proxyURL.User.Username() + ":" + password))
	return "Basic " + token
}

func absoluteFormURL(target *url.URL) *url.URL {
	next := *target
	return &next
}

func originFormURL(target *url.URL) *url.URL {
	next := *target
	next.Scheme = ""
	next.Host = ""
	next.User = nil
	return &next
}

func defaultPortForURL(target *url.URL) string {
	if target.Scheme == "https" {
		return "443"
	}
	return "80"
}

func splitUpstreamAuth(upstream string) (string, string, string) {
	user, password, address, ok := splitUserinfoHost(upstream)
	if !ok {
		return "", "", upstream
	}
	return user, password, address
}

func splitUserinfoHost(value string) (string, string, string, bool) {
	index := strings.LastIndex(value, "@")
	if index < 0 {
		return "", "", value, false
	}
	before, after := value[:index], value[index+1:]
	user, password, _ := strings.Cut(before, ":")
	if decoded, err := url.QueryUnescape(user); err == nil {
		user = decoded
	}
	if decoded, err := url.QueryUnescape(password); err == nil {
		password = decoded
	}
	return user, password, after, true
}

func splitHostPortDefault(address string, defaultPort string) (string, string, error) {
	host, port, err := net.SplitHostPort(address)
	if err == nil {
		return host, port, nil
	}
	if strings.Contains(err.Error(), "missing port in address") {
		return address, defaultPort, nil
	}
	return "", "", err
}

func ensurePort(address string, defaultPort string) string {
	if _, _, err := net.SplitHostPort(address); err == nil {
		return address
	}
	return net.JoinHostPort(address, defaultPort)
}

func copyHeader(dst http.Header, src http.Header) {
	for key, values := range src {
		for _, value := range values {
			dst.Add(key, value)
		}
	}
}

func cloneHeaderWithoutHopByHop(src http.Header) http.Header {
	dst := make(http.Header, len(src))
	for key, values := range src {
		if isHopByHopHeader(key) {
			continue
		}
		dst[key] = append([]string{}, values...)
	}
	return dst
}

func isHopByHopHeader(key string) bool {
	switch http.CanonicalHeaderKey(key) {
	case "Connection", "Keep-Alive", "Proxy-Authenticate", "Proxy-Authorization",
		"Proxy-Connection", "Te", "Trailer", "Transfer-Encoding", "Upgrade":
		return true
	default:
		return false
	}
}

func relay(left net.Conn, right net.Conn) {
	done := make(chan struct{}, 2)
	go func() {
		_, _ = io.Copy(left, right)
		done <- struct{}{}
	}()
	go func() {
		_, _ = io.Copy(right, left)
		done <- struct{}{}
	}()
	<-done
	_ = left.Close()
	_ = right.Close()
	<-done
}
